version: '2'
services:
    universitydatalookupapp-app:
        image: universitydatalookupapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://universitydatalookupapp-mysql:3306/universitydatalookupapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    universitydatalookupapp-mysql:
        extends:
            file: mysql.yml
            service: universitydatalookupapp-mysql
